framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        default_bus: command.bus
        buses:
            command.bus: ~
                #middleware:
                #    - doctrine_transaction
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        routing:
            App\Common\Application\Command\CommandInterface: sync
            App\Common\Application\Query\QueryInterface: sync
            App\Common\Domain\Event\EventInterface: async

        #routing:
        #    Symfony\Component\Mailer\Messenger\SendEmailMessage: async
        #    Symfony\Component\Notifier\Message\ChatMessage: async
        #    Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
