twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        - '%kernel.project_dir%/ui/back/templates'
        - '%kernel.project_dir%/ui/front/templates'

when@test:
    twig:
        strict_variables: true
