image: composer:2.0.11

stages:
    - build
    - test
    - deploy

variables:
    DOCKER_DRIVER: overlay2

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .env
        - vendor/
        - bin/.phpunit
        - var/cache
        - public/build

before_script:
    - composer install --ignore-platform-reqs --no-ansi --no-interaction --no-scripts
    - echo "APP_SECRET=$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 32)" >> .env

build-php:
    stage: build
    script:
        - composer dump-autoload --optimize --classmap-authoritative
        - composer check-platform-reqs

build-js:
    image: node:15.11.0-alpine3.13
    before_script: []
    stage: build
    script:
        - yarn install
        - yarn build

codestyle:
    stage: test
    script:
        - php -d memory_limit=-1 ./bin/console cache:warmup --env=dev
        - php -d memory_limit=-1 ./vendor/bin/phpcs --standard=phpcs.xml
        - php -d memory_limit=-1 ./vendor/bin/phpcpd --fuzzy src/ tests/ config/
        - php -d memory_limit=-1 ./vendor/bin/phpstan analyse -c phpstan.neon --no-progress

test:
    stage: test
    script:
        - php -d memory_limit=-1 ./bin/console cache:warmup --env=test
        - php -d memory_limit=-1 ./bin/phpunit
        - php -d memory_limit=-1 ./vendor/bin/phpstan analyse -c phpstan-tests.neon --no-progress

deploy:
    image: docker/compose
    before_script: []
    services:
        - docker:dind
    stage: deploy
    script:
        - docker-compose -f docker-compose.prod.yml up -d --build
    only:
        - master
    when: manual

