image: php:8.0.3-cli-alpine3.13

stages:
    - build
    - test
    - deploy

variables:
    DOCKER_DRIVER: overlay2

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - vendor/
        - bin/.phpunit
        - var/cache

.before:
    before_script:
        - cp .env.example .env
        - sed -i "s/ThisTokenIsNotSecretChangeIt/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)/g" .env

build:
    image: composer:2.0.11
    extends: .before
    stage: build
    script:
        - composer install --ignore-platform-reqs --no-ansi --no-interaction --no-scripts

codestyle:
    extends: .before
    stage: test
    script:
        - php -d memory_limit=-1 ./bin/console cache:warmup --env=dev
        - php -d memory_limit=-1 ./vendor/bin/phpcs --standard=phpcs.xml
        - php -d memory_limit=-1 ./vendor/bin/phpcpd --fuzzy src/ tests/ config/
        - php -d memory_limit=-1 ./vendor/bin/phpstan analyse -c phpstan.neon --no-progress

test:
    image: composer:2.0.11
    extends: .before
    stage: test
    script:
        - php -d memory_limit=-1 ./bin/console cache:warmup --env=test
        - php -d memory_limit=-1 ./bin/phpunit
        - php -d memory_limit=-1 ./vendor/bin/phpstan analyse -c phpstan-tests.neon --no-progress

deploy:
    image: docker/compose
    services:
        - docker:dind
    stage: deploy
    script:
        - docker-compose -f docker-compose.prod.yml up -d --build
    only:
        - master
    when: manual

