http:
    address: "0.0.0.0:1070"

    uploads:
        forbid: [".php", ".exe", ".bat"]

    workers:
        command: "php bin/console baldinof:roadrunner:worker"
        relay: "unix://var/roadrunner.sock"

    ssl:
        redirect: true
        port: 443

        cert: /etc/roadrunner/ssl/server.crt
        key: /etc/roadrunner/ssl/private/server.key

static:
    dir:   "public"
    forbid: [".php", ".htaccess"]
