version: "3.4"

services:
    web:
        image: boilerplate:latest
        container_name: web
        build:
            context: .
            target: common
            args:
                - ENVIRONMENT=dev
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
