version: "3.4"

services:
    web:
        image: boilerplate:latest
        container_name: web
        build:
            context: .
            target: dev
            args:
                - ENVIRONMENT=dev
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
        depends_on:
            - consume
            - rabbitmq

    consume:
        image: boilerplate:latest
        restart: always
        container_name: consume
        entrypoint: php bin/console messenger:consume --limit=10 -vv

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui

    rabbitmq:
        image: rabbitmq:3.8-management
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - 5672:5672 # dsn server
            - 15672:15672 # web ui