version: "3.4"

services:
    web:
        image: boilerplate:latest
        container_name: web
        build:
            context: .
            target: prod
            args:
                - ENVIRONMENT=prod
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.web.entryPoints=websecure"
            - "traefik.http.routers.web.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.web.middlewares=basic-auth@file" # dont forget remove this after app will be ready for prod
        networks:
            - proxy

networks:
    proxy:
        external: true
