version: "3.4"

services:
    web:
        image: boilerplate:latest
        container_name: web
        build:
            context: .
            target: prod
        environment:
            - APP_ENV=prod
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.web.entryPoints=websecure"
            - "traefik.http.routers.web.rule=Host(`${DOMAIN}`)"
        networks:
            - proxy

networks:
    proxy:
        external: true
