version: "3.4"

services:
    web:
        image: boilerplate:latest
        container_name: web
        build:
            context: .
            target: prod
            args:
                - ENVIRONMENT=prod
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.web.entryPoints=websecure"
            - "traefik.http.routers.web.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.web.middlewares=basic-auth@file" # dont forget remove this after app will be ready for prod
        networks:
            - proxy
        environment:
            - CORE_MAILER_DSN=${CORE_MAILER_DSN}
            - CORE_MAILER_EMAIL=${CORE_MAILER_EMAIL}
            - CORE_TRANSPORT_DSN=${CORE_TRANSPORT_DSN}
        depends_on:
            - rabbitmq

    consume:
        image: boilerplate:latest
        container_name: consume
        restart: always
        entrypoint: php bin/console messenger:consume --limit=10 -vv

    rabbitmq:
        image: rabbitmq:3.8-management
        container_name: rabbitmq
        volumes:
            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=${TRANSPORT_USERNAME}
            - RABBITMQ_DEFAULT_PASS=${TRANSPORT_PASSWORD}
        ports:
            - 5672:5672

networks:
    proxy:
        external: true
