version: "3.4"

services:
    web:
        image: boilerplate:latest
        container_name: web
        build:
            context: .
            target: dev
            args:
                - ENVIRONMENT=dev
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80

    mailhog:
        image: mailhog/mailhog
        ports:
            - '1025:1025' # smtp server
            - '8025:8025' # web ui