version: "3.4"

services:
    web:
        image: boilerplate:latest
        container_name: web
        build:
            context: .
            target: prod
            args:
                - ENVIRONMENT=prod
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.web.entryPoints=websecure"
            - "traefik.http.routers.web.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.web.middlewares=basic-auth@file" # dont forget remove this after app will be ready for prod
        environment:
            - CORE_MAILER_DSN=${CORE_MAILER_DSN}
            - CORE_MAILER_EMAIL=${CORE_MAILER_EMAIL}
            - CORE_TRANSPORT_DSN=${CORE_TRANSPORT_DSN}
        networks:
            - proxy
        depends_on:
            - rabbitmq

    worker:
        image: boilerplate:latest
        container_name: worker
        restart: always
        entrypoint: php bin/console messenger:consume --limit=10 -vv
        environment:
            - CORE_MAILER_DSN=${CORE_MAILER_DSN}
            - CORE_MAILER_EMAIL=${CORE_MAILER_EMAIL}
            - CORE_TRANSPORT_DSN=${CORE_TRANSPORT_DSN}
        networks:
            - proxy
        depends_on:
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3.8-management
        container_name: rabbitmq
        volumes:
            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=${TRANSPORT_USERNAME}
            - RABBITMQ_DEFAULT_PASS=${TRANSPORT_PASSWORD}
        networks:
            - proxy
        ports:
            - 5672:5672

    mariadb:
        image: mariadb:10.4.18
        container_name: mariadb
        restart: always
        volumes:
            - ./.docker/mysql/data/:/var/lib/mysql
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            - proxy

networks:
    proxy:
        external: true
