version: "3"

services:
    web:
        image: boilerplate:latest
        container_name: web
        build:
            context: .
            target: dev
            args:
                - ENVIRONMENT=dev
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
        depends_on:
            - mariadb
            - rabbitmq

    worker:
        image: boilerplate:latest
        container_name: worker
        restart: always
        entrypoint: php bin/console messenger:consume async --limit=10 -vv
        depends_on:
            - mariadb
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3.8.17-management
        container_name: rabbitmq
        ports:
            - 5672:5672 # dsn server
            - 15672:15672 # web ui

    mariadb:
        image: mariadb:10.4.18
        container_name: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=localhost
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    redis:
        image: redis:6.2.3-alpine
        container_name: redis
        ports:
            - 6379:6379

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080 # web ui

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
