rest:
    resource: ../../ui/rest/Controller/
    type: annotation

back:
    resource: ../../ui/back/Controller/
    type: annotation

front:
    resource: ../../ui/front/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
