rest:
    prefix: /api
    resource: ../../ui/rest/Controller/
    type: annotation

back:
    prefix: /backoffice
    name_prefix: backoffice.
    resource: ../../ui/http/Back/
    type: annotation

front:
    resource: ../../ui/http/Front/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
